language: python

python:
  - "3.2"

install:
  - pip install pytvdbapi --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install vvv --use-mirrors

script: pep8 -r --statistics --count --ignore=E501 .; vvv .
